---
# Run `dnf update` on host to update all packages
- name: Update all packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_only: true

- name: Remove packages defined by remove_packages variable
  ansible.builtin.dnf:
    name: "{{ remove_packages }}"
    state: absent

- name: Install packages post-upgrade defined by install_packages variable
  ansible.builtin.dnf:
    name: "{{ install_packages }}"
    state: present