---
- name: leapp-multiple-kernel-devels-installed | Set leapp-entry if leapp-report contains this inhibitor
  ansible.builtin.set_fact:
    leapp_entry: "{{ item }}"
  loop: "{{ leapp_report_json.entries }}"
  when: item.key == entry_key

- block:
    - name: leapp-multiple-kernel-devels-installed | Get list of installed kernel-devel packages
      ansible.builtin.shell: |
        rpm -q kernel-devel --queryformat '%{version}-%{release}.%{arch}\n' | sort -Vr
      register: installed_kernel_devels
      changed_when: true

    - name: leapp-multiple-kernel-devels-installed | Get current kernel version
      ansible.builtin.command: uname -r
      register: current_kernel
      changed_when: true

    - name: leapp-multiple-kernel-devels-installed | Remove extra kernel-devel packages
      ansible.builtin.yum:
        name: "kernel-devel-{{ item }}"
        state: absent
      when: item != current_kernel.stdout
      loop: "{{ installed_kernel_devels.stdout_lines }}"

  when:
    - leapp_entry is defined
    - leapp_entry.key == entry_key
    - ansible_fqdn == leapp_entry.hostname
