---
- name: leapp-multiple-kernel-debugs-installed | Set leapp-entry if leapp-report contains this inhibitor
  ansible.builtin.set_fact:
    leapp_entry: "{{ item }}"
  loop: "{{ leapp_report_json.entries }}"
  when: item.key == entry_key

- block:
    - name: leapp-multiple-kernel-debugs-installed | Get list of installed kernel-debug packages
      ansible.builtin.shell: |
        rpm -q kernel-debug --queryformat '%{version}-%{release}.%{arch}\n' | sort -Vr
      register: installed_kernel_debugs
      changed_when: true

    - name: leapp-multiple-kernel-debugs-installed | Get current kernel version
      ansible.builtin.command: uname -r
      register: current_kernel
      changed_when: true

    - name: leapp-multiple-kernel-debugs-installed | Remove extra kernel-debug packages
      ansible.builtin.yum:
        name: "kernel-debug-{{ item }}"
        state: absent
      when: item != current_kernel.stdout
      loop: "{{ installed_kernel_debugs.stdout_lines }}"

  when:
    - leapp_entry is defined
    - leapp_entry.key == entry_key
    - ansible_fqdn == leapp_entry.hostname
