---
- name: leapp-unmount-nfs-shares | Set leapp-entry if leapp-report contains this inhibitor
  ansible.builtin.set_fact:
    leapp_entry: "{{ item }}"
  loop: "{{ leapp_report._json.entries }}"
  when: item.key == entry_key

- block:
    # Gives us a list of NFS mounts unique to this host, and will be used with the ansible.posix.mount module to unmount NFS mounts
    - name: Find all NFS mounts
      ansible.builtin.set_fact:
        nfs_mounts: "{{ ansible_mounts | default([]) | selectattr('fstype', 'in', ['nfs', 'nfs4']) | list }}"

    - name: Backup /etc/fstab
      ansible.builtin.copy:
        src: "/etc/fstab"
        dest: "{{ fstab_backup_path }}"
        remote_src: true
        mode: preserve

    - name: Read /etc/fstab content
      ansible.builtin.slurp:
        path: /etc/fstab
      register: fstab_content

    # Returns a list of all valid NFS entries in /etc/fstab, excludes any commented-out lines
    - name: Decode and parse NFS entries from /etc/fstab
      ansible.builtin.set_fact:
        nfs_entries: "{{ fstab_content.content | b64decode | split('\n') | select('search', 'nfs') | reject('search', '#') | list }}"

    - name: Comment out NFS entries in /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: "^{{ item | regex_escape }}"
        line: "#{{ item }}"
      loop: "{{ nfs_entries }}"

    # Task to unmount all active mounts defined in nfs_mounts
    - name: Unmount all mounts defined in nfs_mounts
      ansible.posix.mount:
        path: "{{ item['mount'] }}"
        state: unmounted
      loop: "{{ nfs_mounts }}"
  when:
    - leapp_entry is defined
    - leapp_entry.key == entry_key
    - ansible_fqdn == leapp_entry.hostname
